deviceId=1
serialPortName=COM11
#serialReadByteTimeout=150
#serialWriteByteDelay=150
serialReadByteTimeout=100
serialWriteByteDelay=0
#*** logLevel 0:no 1:warning 2:normal(default) 3:full ***#
#logLevel=2
#openPortDelay=3000
#closePortDelay=0