#com.uniinformation.estimation.database.dbHost=152.101.145.68
#com.uniinformation.estimation.database.dbPort=6002
#com.uniinformation.estimation.database.dbName=est_ctps
#com.uniinformation.estimation.database.dbHost=152.101.145.68
#com.uniinformation.estimation.database.dbPort=16002
#com.uniinformation.estimation.database.dbName=est_ctps

#dev183
com.uniinformation.estimation.database.dbHost=210.3.102.3
com.uniinformation.estimation.database.dbPort=3102
#est_ctps
com.uniinformation.estimation.database.dbName=est_ctps
#wip
#com.uniinformation.estimation.database.dbName=wip

#gbp-javaproxy
#com.uniinformation.estimation.database.dbHost=210.3.102.2
#com.uniinformation.estimation.database.dbPort=16002
#com.uniinformation.estimation.database.dbName=est_ctps

#com.uniinformation.estimation.database.dbHost=localhost
#com.uniinformation.estimation.database.dbPort=6102
#com.uniinformation.estimation.database.dbName=est_ctps
com.uniinformation.estimation.skipDeliveryCost=Y
com.uniinformation.estimation.maxMatSize=9999.0
com.uniinformation.estimation.customizedBindOption=Y