log4j.logger.zkbiaccess=ALL, zkbiaccessAppender, zkbiconsoleAppender
log4j.logger.zkbidebug=ALL, zkbidebugAppender, zkbiconsoleAppender

log4j.additivity.access=false
log4j.additivity.debug=false
log4j.additivity.console=false

log4j.appender.zkbiaccessAppender=org.apache.log4j.RollingFileAppender
log4j.appender.zkbiaccessAppender.File=/tmp/zkbi_access.log
log4j.appender.zkbiaccessAppender.MaxFileSize=1MB
log4j.appender.zkbiaccessAppender.MaxBackupIndex=5
log4j.appender.zkbiaccessAppender.layout=org.apache.log4j.PatternLayout
log4j.appender.zkbiaccessAppender.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1} - %m%n

log4j.appender.zkbidebugAppender=org.apache.log4j.RollingFileAppender
log4j.appender.zkbidebugAppender.File=/tmp/zkbi_debug.log
log4j.appender.zkbidebugAppender.MaxFileSize=1MB
log4j.appender.zkbidebugAppender.MaxBackupIndex=5
log4j.appender.zkbidebugAppender.layout=org.apache.log4j.PatternLayout
log4j.appender.zkbidebugAppender.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1} - %m%n


log4j.appender.zkbiconsoleAppender=org.apache.log4j.ConsoleAppender
log4j.appender.zkbiconsoleAppender.Target=System.out
log4j.appender.zkbiconsoleAppender.layout=org.apache.log4j.PatternLayout
log4j.appender.zkbiconsoleAppender.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1} - %m%n

log4j.logger.org.apache.pdfbox=ERROR
log4j.logger.org.apache.fontbox=ERROR