# your Saleor GraphQL endpoint
saleor.graphql-url=http://localhost:8000/graphql/

# (these still work when running as a JAR in dev; they are ignored by external Tomcat)
server.port=8081
server.servlet.context-path=/sync

# GraphQL HTTP endpoint (default is /graphql)
spring.graphql.path=/graphql
spring.graphql.graphiql.path=/graphiql
# Built-in GraphiQL UI (handy for testing at /graphiql)
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.cdn.enabled=true   # load GraphiQL assets from CDN
# For Swagger UI (springdoc)
springdoc.api-docs.path=/v3/api-docs
# Boot 2.7: UI at /swagger-ui.html

sync.enabled=false
dbtest.enabled=false


#spring.datasource.url=jdbc:postgresql://192.168.46.104:5433/aivectordb
#spring.datasource.username=aiadmin
#spring.datasource.password=!2N3055mj2955

#spring.datasource.url=jdbc:postgresql://192.168.46.112:5432/openai_embeddings
#spring.datasource.username=postgres
#spring.datasource.password=el2301HK
#spring.datasource.hikari.maximum-pool-size=10
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#spring.main.banner-mode=off

#app.tcp.servers[0].name=loopbackserver
#app.tcp.servers[0].port=6021
#app.tcp.servers[0].backlog=200
#app.tcp.servers[0].workerCore=16
#app.tcp.servers[0].workerMax=kkk32
#app.tcp.servers[0].queueCapacity=500
#app.tcp.servers[0].clientReadTimeoutMs=30000
#app.tcp.servers[0].handlerBean=loopBackTcpHandler

app.tcp.servers[0].name=bicoreserver
app.tcp.servers[0].port=6021
app.tcp.servers[0].backlog=200
app.tcp.servers[0].workerCore=16
app.tcp.servers[0].workerMax=32
app.tcp.servers[0].queueCapacity=500
app.tcp.servers[0].clientReadTimeoutMs=30000
app.tcp.servers[0].handlerBean=BiRpcServerTcpHandler


app.tcp.servers[1].name=saleorsyncrpc
app.tcp.servers[1].port=6022
app.tcp.servers[1].backlog=200
app.tcp.servers[1].workerCore=32
app.tcp.servers[1].workerMax=64
app.tcp.servers[1].queueCapacity=1000
app.tcp.servers[1].clientReadTimeoutMs=20000
app.tcp.servers[1].handlerBean=rpcServerTcpHandler