package com.uniinformation.bicore.erpv4;

import java.util.Collections;
import java.util.Date;
import java.util.HashSet;
import java.util.Hashtable;
import java.util.Vector;

import com.kyoko.common.DateUtil;
import com.kyoko.common.ReturnMsg;
import com.kyoko.common.StringUtil;
import com.uniinformation.bicore.BiCellCollection;
import com.uniinformation.bicore.BiResult;
import com.uniinformation.bicore.BiTable;
import com.uniinformation.bicore.BiView;
import com.uniinformation.bicore.ColumnCell;
import com.uniinformation.cell.CellCollection;
import com.uniinformation.cell.CellException;
import com.uniinformation.erpv4.Erpv4Config;
import com.uniinformation.erpv4.GenbucketUtil;
import com.uniinformation.rpccall.RpcClient;
import com.uniinformation.rpccall.Strval;
import com.uniinformation.rpccall.Value;
import com.uniinformation.utils.SelectUtil;
import com.uniinformation.utils.TableRec;
import com.uniinformation.utils.UniLog;
import com.uniinformation.utils.VectorUtil;
import com.uniinformation.utils.Wherecl;
import com.uniinformation.webcore.SessionHelper;

public class BiResultGlTran extends BiResultErpv4 {

	public BiResultGlTran(BiResult p_parent, BiView p_view, SelectUtil p_su, Vector p_tabList, String p_whereStr,
			SessionHelper p_sh) throws CellException {
		super(p_parent, p_view, p_su, p_tabList, p_whereStr, p_sh);
		// TODO Auto-generated constructor stub
	}

	@Override
	protected HashSet<BiTable> addExtraWhereStr(Wherecl p_where,HashSet<BiTable> p_hash)
	{
		HashSet<BiTable> ht = super.addExtraWhereStr(p_where, p_hash);
		if(Erpv4Config.isMultiCompany(sh)) {
			String cocode = Erpv4Config.getDefaultCoCode(sh);
			if(getCell("tr_cocode") != null) {
				Wherecl wcl1 = new Wherecl();
				wcl1.appendString(" and tr_cocode = '"+cocode+"' ").stripAnd();
				p_where.andWherecl(wcl1);
				if(ht == null) {
					ht = new HashSet<BiTable>();
				}
			}
			return(ht);
		} else return(ht);
	}
	
	@Override
	protected void afterFetch() {
		try {
			getCell("tr_plamount").eval();
			getCell("tr_nlamount").eval();
		} catch (CellException cex) {
			UniLog.log(cex);
		}
	}
	
	@Override
	protected ReturnMsg biBeforeAddUpdateCurrent(BiCellCollection col,boolean isUpdate) {
		ReturnMsg rtn = super.biBeforeAddUpdateCurrent(col, isUpdate);
		if(rtn != null && !rtn.getStatus()) return(rtn);
		if(Math.abs(getCell("tr_plamount").getDouble() + getCell("tr_nlamount").getDouble()) > 0.000001) {
				return(new ReturnMsg(false,"Transaction Not Balance"));
		}
		if(getCellString("tr_srcno").equals("")) {
			RpcClient rpc = getSelectUtil().getRpcClient();
			rpc.callSegment("setCocodeBaseccy",
							new VectorUtil()
							.addElement(
//										Erpv4Config.getCoCode(getSessionHelper()) 
										col.getCellString("tr_cocode")
								)
							.addElement(
									Erpv4Config.getBaseCcy(getSessionHelper(),col.getCellString("tr_cocode"))
									)
							.toVector()
							);
			Value val = rpc.callSegment("getrg_byrgcontrol_bycategory",
				new VectorUtil()
				.addElement("glvh")
				.addElement(getCell("tr_xdate").getDate())
				.toVector()
				);
			if(val == null || !(val instanceof Strval)) {
				return(new ReturnMsg(false,"Error : get voucher number failed"));
			}
			try {
				getCell("tr_srcno").set(val.toString().trim());
			} catch (CellException cex) {
				UniLog.log(cex);
				return(new ReturnMsg(false,"Error : get voucher number failed"));
			}
		}
		return(ReturnMsg.defaultOk);
	}
	@Override
	public String getLinkedView(String p_colName,CellCollection col) {
		if(p_colName.equals("tr_srcno")) {
			String jn = col.getCellString("tr_jcode");
			if(jn.equals("AR")) return("erpv4.SihAr");
			if(jn.equals("AP")) return("erpv4.SihAp");
			if(jn.equals("PR")) return("erpv4.CrhAr");
			if(jn.equals("PP")) return("erpv4.CrhAp");
		}
		return(super.getLinkedView(p_colName,col));
	}

	@Override
	public String getLinkedColumn(String p_colName) {
		if(p_colName.equals("tr_srcno")) {
			String jn = getCellString("tr_jcode");
			if(jn.equals("AR")) return("sih_sno");
			if(jn.equals("AP")) return("sih_sno");
			if(jn.equals("PR")) return("crh_voucher");
			if(jn.equals("PP")) return("crh_voucher");
		}
		return(super.getLinkedColumn(p_colName));
	}
	

	@Override
	protected ReturnMsg biBeforeDeleteCurrent(CellCollection col) {
//   		RpcClient rpc = getView().getSchema().getRpcClient();
		ReturnMsg rtn = super.biBeforeDeleteCurrent(col);
		if(rtn != null && !rtn.getStatus()) return(rtn);
		if(col.getCellString("tr_post").equals("P")) {
			return(new ReturnMsg(false,"Cannot Delete Posted Transaction"));
		}
		if(!col.getCellString("tr_jcode").equals("GJ")) {
			return(new ReturnMsg(false,"Cannot Delete Transaction Generated by Other Modules"));
		}
		return(rtn);
	}
	
}
