package com.uniinformation.jxapp.erpv4;

import org.json.JSONObject;
import org.zkoss.zk.ui.Executions;

import com.kyoko.common.ReturnMsg;
import com.kyoko.common.StringUtil;
import com.uniinformation.bicore.BiResult;
import com.uniinformation.cell.Cell;
import com.uniinformation.cell.CellException;
import com.uniinformation.erpv4.Erpv4Config;
import com.uniinformation.jx.JxField;
import com.uniinformation.jx.MessageBoxActionInterface;
import com.uniinformation.jxapp.JxZkBiBase;
import com.uniinformation.rpccall.RpcClient;
import com.uniinformation.rpccall.Value;
import com.uniinformation.utils.UniLog;
import com.uniinformation.utils.VectorUtil;
import com.uniinformation.webcore.SessionHelper;

public class GlTran extends JxZkBiBase {
	@Override public void afterBind() {
		super.afterBind();
		displayOnlyWhenUpdate = true;
		new JxFieldAction("btCopyTran") {
			@Override
			public void actionPerformed(JxField jxfield) {
				
				// TODO Auto-generated method stub
				
				confirm("Do you want to copy this order ?", 
						new MessageBoxActionInterface() {
							public void onButtonClicked( Object p_obj) {
								try {
									if(((Integer) p_obj).intValue() == 1) {
										
				RpcClient rpc = getSessionHelper().getRpcClient();
				
				rpc.callSegment("setCocodeBaseccy",
						new VectorUtil()
						.addElement(
//									Erpv4Config.getCoCode(getSessionHelper()) 
									getBr().getCellString("tr_cocode")
							)
						.addElement(
								Erpv4Config.getBaseCcy(getSessionHelper(),getBr().getCellString("tr_cocode"))
								)
						.toVector()
						);	
				Value v = rpc.callSegment(
						"erpv4_cloneGlTran",
						new VectorUtil()
							.addElement(getBr().getCellInt("tr_xno"))
							.toVector()
						);
				rpc.close();
				if(v != null && v.toString().startsWith("OK")) {

					try {
						int xno = Integer.parseInt(StringUtil.strpart(v.toString(), 4, 10).trim());
						String visitUrl = SessionHelper.getUrlByViewid(getSessionHelper(), "erpv4.GlTran");
						JSONObject jo = new JSONObject();
						jo.put("customCondition","tr_xno = " + xno);
						String key = sessionHelper.putOneTimeData( jo);
						String url = visitUrl + "&querycondition="+key;
						Executions.sendRedirect(url);
						
					} catch (Exception ex) {
						UniLog.log(ex);
					}
				} else {
					
					messageBox("Copy Transaction Failed " + v == null ? "null" : v.toString());
				}
										
									}
								} catch (Exception ex)  {
									UniLog.log(ex);
								}
							}
						}
					);		
				
				
			}
		};
	}

	@Override
	public void bindCellCollection(BiResult p_br,int mode) {
		super.bindCellCollection(p_br, mode);
		if(!p_br.getCellString("tr_jcode").equals("GJ")) {
			try {
				p_br.getCell("tr_xdate").setMode(Cell.VMODE_DISPONLY);
				p_br.getCell("tr_srcno").setMode(Cell.VMODE_DISPONLY);
			} catch (Exception cex) {
				UniLog.log(cex);
			}
		}
	}
	@Override
	protected ReturnMsg allowDisplayToUpdate() {
		if(
				(!getBr().getCellString("tr_jcode").equals("GJ"))
					||
				(getBr().getCellString("tr_post").equals("P"))
				) {
			return(new ReturnMsg(false,"Cannot Edit Transaction Generated by Other Modules or Posted Trans"));
		}
		return(ReturnMsg.defaultOk);
	}
}
