/* The following code was generated by JFlex 1.3.5 on 1/12/24 6:22 PM */

package com.uniinformation.utils.whereclpar;
import java.io.*;
import com.uniinformation.utils.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 1/12/24 6:22 PM from the specification file
 * <tt>file:/yic/v/unidev/src/com/uniinformation/utils/whereclpar/calc.flex</tt>
 */
class Yylex {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int STRINGLITERAL = 1;
  final public static int STRINGLITERAL2 = 2;
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\10\0\1\50\1\47\1\3\2\0\1\4\22\0\1\47\1\33\1\51"+
    "\3\0\1\6\1\52\1\46\1\46\1\46\1\46\1\46\1\46\1\2"+
    "\1\46\12\1\2\0\1\32\1\31\1\30\2\0\1\12\2\5\1\14"+
    "\11\5\1\13\1\20\2\5\1\21\10\5\1\46\1\53\1\46\1\46"+
    "\1\5\1\0\1\7\1\41\1\35\1\11\1\24\1\25\1\43\1\36"+
    "\1\37\1\5\1\40\1\26\1\34\1\10\1\16\1\45\1\5\1\17"+
    "\1\27\1\22\1\23\1\5\1\42\1\44\2\5\1\0\1\15\uff83\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    44,    88,   132,   176,   220,   264,   308,   352,   396, 
      440,   484,   528,   572,   616,   660,   704,   748,   792,   836, 
      880,   924,   968,  1012,  1056,  1100,   220,  1144,   220,   220, 
      220,  1188,   220,  1232,  1276,  1320,   176,   220,  1364,  1408, 
     1452,  1496,   220,   308,  1540,  1584,  1628,  1672,   220,   220, 
      220,   220,  1716,   308,   308,  1760,   220,   220,   220,   308, 
      308,  1804,  1848,  1892,  1936,  1980,  2024,  2068,   308,  2112, 
      308,  2156,   308,  2200,  2244,  2288,   308,  2332,  2376,   308, 
     2420,  2464,   308,   308
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\0\1\4\1\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\10\1\14\2\10\1\15\1\16\1\17\1\20"+
    "\1\10\1\21\2\10\1\22\1\23\1\10\1\24\1\25"+
    "\1\26\1\27\1\30\2\10\1\31\1\10\1\32\4\10"+
    "\1\33\1\34\1\35\1\36\1\37\1\0\51\40\1\41"+
    "\1\40\1\42\52\43\1\41\1\44\1\0\1\4\1\45"+
    "\52\0\1\45\131\0\1\6\51\0\2\10\2\0\1\10"+
    "\1\0\6\10\1\0\12\10\4\0\12\10\14\0\1\46"+
    "\46\0\2\10\2\0\1\10\1\0\1\10\1\47\4\10"+
    "\1\0\12\10\4\0\12\10\7\0\2\10\2\0\1\10"+
    "\1\0\6\10\1\0\1\50\4\10\1\51\4\10\4\0"+
    "\12\10\7\0\2\10\2\0\1\10\1\0\4\10\1\52"+
    "\1\10\1\0\12\10\4\0\12\10\23\0\1\53\37\0"+
    "\2\10\2\0\1\10\1\0\6\10\1\0\1\10\1\54"+
    "\10\10\4\0\12\10\7\0\2\10\2\0\1\10\1\0"+
    "\6\10\1\0\6\10\1\55\3\10\4\0\12\10\7\0"+
    "\2\10\2\0\1\10\1\0\6\10\1\0\3\10\1\54"+
    "\6\10\4\0\12\10\7\0\2\10\2\0\1\10\1\0"+
    "\6\10\1\0\1\10\1\56\10\10\4\0\12\10\7\0"+
    "\2\10\2\0\1\10\1\0\1\57\5\10\1\0\12\10"+
    "\4\0\12\10\7\0\2\10\2\0\1\10\1\0\6\10"+
    "\1\0\12\10\4\0\3\10\1\60\6\10\37\0\1\61"+
    "\53\0\1\62\52\0\1\63\1\64\53\0\1\63\23\0"+
    "\2\10\2\0\1\10\1\0\1\65\5\10\1\0\12\10"+
    "\4\0\12\10\7\0\2\10\2\0\1\10\1\0\1\10"+
    "\1\66\4\10\1\0\11\10\1\67\4\0\12\10\7\0"+
    "\2\10\2\0\1\10\1\0\6\10\1\0\6\10\1\70"+
    "\3\10\4\0\12\10\55\0\1\34\4\0\51\40\1\0"+
    "\1\40\52\0\1\71\1\0\1\72\52\43\54\0\1\73"+
    "\1\72\1\0\2\10\2\0\1\10\1\0\2\10\1\74"+
    "\3\10\1\0\12\10\4\0\12\10\7\0\2\10\2\0"+
    "\1\10\1\0\6\10\1\0\4\10\1\75\5\10\4\0"+
    "\12\10\7\0\2\10\2\0\1\10\1\0\6\10\1\0"+
    "\10\10\1\76\1\10\4\0\12\10\7\0\2\10\2\0"+
    "\1\10\1\0\5\10\1\74\1\0\12\10\4\0\12\10"+
    "\7\0\2\10\2\0\1\10\1\0\6\10\1\0\12\10"+
    "\4\0\7\10\1\77\2\10\7\0\2\10\2\0\1\10"+
    "\1\0\6\10\1\0\5\10\1\100\4\10\4\0\12\10"+
    "\7\0\2\10\2\0\1\10\1\0\6\10\1\0\10\10"+
    "\1\101\1\10\4\0\12\10\7\0\2\10\2\0\1\10"+
    "\1\0\6\10\1\0\12\10\4\0\4\10\1\102\5\10"+
    "\7\0\2\10\2\0\1\10\1\0\6\10\1\0\4\10"+
    "\1\103\5\10\4\0\12\10\7\0\2\10\2\0\1\10"+
    "\1\0\6\10\1\0\4\10\1\104\5\10\4\0\12\10"+
    "\7\0\2\10\2\0\1\10\1\0\6\10\1\0\10\10"+
    "\1\105\1\10\4\0\12\10\7\0\2\10\2\0\1\10"+
    "\1\0\6\10\1\0\6\10\1\106\3\10\4\0\12\10"+
    "\7\0\2\10\2\0\1\10\1\0\6\10\1\0\6\10"+
    "\1\107\3\10\4\0\12\10\7\0\2\10\2\0\1\10"+
    "\1\0\6\10\1\0\11\10\1\110\4\0\12\10\7\0"+
    "\2\10\2\0\1\10\1\0\6\10\1\0\6\10\1\111"+
    "\3\10\4\0\12\10\7\0\2\10\2\0\1\10\1\0"+
    "\6\10\1\0\12\10\4\0\1\10\1\112\10\10\7\0"+
    "\2\10\2\0\1\10\1\0\6\10\1\0\12\10\4\0"+
    "\6\10\1\113\3\10\7\0\2\10\2\0\1\10\1\0"+
    "\6\10\1\0\12\10\4\0\10\10\1\114\1\10\7\0"+
    "\2\10\2\0\1\10\1\0\6\10\1\0\6\10\1\115"+
    "\3\10\4\0\12\10\7\0\2\10\2\0\1\10\1\0"+
    "\6\10\1\0\12\10\4\0\2\10\1\116\7\10\7\0"+
    "\2\10\2\0\1\10\1\0\6\10\1\0\6\10\1\117"+
    "\3\10\4\0\12\10\7\0\2\10\2\0\1\10\1\0"+
    "\6\10\1\0\12\10\4\0\11\10\1\120\7\0\2\10"+
    "\2\0\1\10\1\0\6\10\1\0\6\10\1\121\3\10"+
    "\4\0\12\10\7\0\2\10\2\0\1\10\1\0\6\10"+
    "\1\0\6\10\1\122\3\10\4\0\12\10\7\0\2\10"+
    "\2\0\1\10\1\0\6\10\1\0\11\10\1\123\4\0"+
    "\12\10\7\0\2\10\2\0\1\10\1\0\1\10\1\124"+
    "\4\10\1\0\12\10\4\0\12\10\6\0";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  0,  0,  1,  0,  9,  1,  1,  0,  1,  1,  1,  0,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  9,  1,  9,  9,  9,  1, 
     9,  0,  1,  0,  1,  9,  1,  1,  1,  1,  9,  1,  1,  1,  1,  1, 
     9,  9,  9,  9,  1,  1,  1,  1,  9,  9,  9,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
  StringBuffer sb = new StringBuffer();
  private Parser yyparser;

  public Yylex(java.io.Reader r, Parser yyparser) {
    this(r);
    this.yyparser = yyparser;
  }
	public int getCurrentPos() {
  		return(yy_currentPos);
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Yylex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[2508];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 140) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 31: 
          {  sb.append(yytext()); UniLog.log("xxx");  }
        case 85: break;
        case 82: 
          {  return Parser.MATCHES;  }
        case 86: break;
        case 79: 
          {  return Parser.T_REGEXP;  }
        case 87: break;
        case 3: 
          {  yyparser.yylval = new ParserVal(Integer.parseInt(yytext()));
         return Parser.INT;  }
        case 88: break;
        case 29: 
          {  sb.setLength(0); yybegin(STRINGLITERAL);  }
        case 89: break;
        case 30: 
          {  sb.setLength(0); yybegin(STRINGLITERAL2);  }
        case 90: break;
        case 57: 
          {  sb.append("\\");  }
        case 91: break;
        case 56: 
          {  sb.append("\"");  }
        case 92: break;
        case 51: 
          {  return Parser.LE;  }
        case 93: break;
        case 50: 
          {  return Parser.NE;  }
        case 94: break;
        case 48: 
          {  return Parser.GE;  }
        case 95: break;
        case 42: 
        case 43: 
          {  return Parser.OR;  }
        case 96: break;
        case 21: 
          {  return Parser.LT;  }
        case 97: break;
        case 20: 
        case 49: 
          {  return Parser.EQ;  }
        case 98: break;
        case 19: 
          {  return Parser.GT;  }
        case 99: break;
        case 26: 
          {  return (int) yycharat(0);  }
        case 100: break;
        case 5: 
        case 6: 
          {   }
        case 101: break;
        case 27: 
          {   }
        case 102: break;
        case 28: 
          {  System.err.println("Sorry, backspace doesn't work");  }
        case 103: break;
        case 34: 
          {  sb.append(yytext());  }
        case 104: break;
        case 7: 
        case 9: 
        case 10: 
        case 11: 
        case 13: 
        case 14: 
        case 15: 
        case 16: 
        case 17: 
        case 18: 
        case 23: 
        case 24: 
        case 25: 
        case 38: 
        case 39: 
        case 40: 
        case 41: 
        case 44: 
        case 45: 
        case 46: 
        case 47: 
        case 52: 
        case 55: 
        case 61: 
        case 62: 
        case 63: 
        case 64: 
        case 65: 
        case 66: 
        case 67: 
        case 69: 
        case 71: 
        case 73: 
        case 74: 
        case 75: 
        case 77: 
        case 78: 
        case 80: 
        case 81: 
          {  
         yyparser.yylval = new ParserVal(new LexIdent(yytext()));
         return Parser.IDENT;  }
        case 105: break;
        case 76: 
          {  return Parser.FALSE;  }
        case 106: break;
        case 68: 
          {  return Parser.T_NULL;  }
        case 107: break;
        case 60: 
          {  return Parser.T_NOT;  }
        case 108: break;
        case 83: 
          {  return Parser.T_BETWEEN;  }
        case 109: break;
        case 72: 
          {  return Parser.LIKE;  }
        case 110: break;
        case 70: 
          {  return Parser.TRUE;  }
        case 111: break;
        case 54: 
          {  return Parser.T_IS;  }
        case 112: break;
        case 53: 
          {  return Parser.T_IN;  }
        case 113: break;
        case 22: 
          {  return Parser.NOT;  }
        case 114: break;
        case 32: 
          {  yybegin(YYINITIAL); 
          yyparser.yylval = new ParserVal(sb.toString());
          return Parser.STRING;
	      }
        case 115: break;
        case 37: 
        case 59: 
          {  return Parser.AND;  }
        case 116: break;
        case 36: 
          {  yyparser.yylval = new ParserVal(Double.parseDouble(yytext()));
         return Parser.NUM;  }
        case 117: break;
        case 58: 
          {  sb.append("'");  }
        case 118: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              { return 0; }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
