package com.uniinformation.jx;
import java.util.*;
import java.text.*;
import com.uniinformation.utils.*;
//import com.uniinformation.jxapp.*;
public interface JxFieldFlowInterface {
   final public static int afEllipse = 0; 
   final public static int afRectangle = 1; 
   final public static int afRoundRect = 2; 
   final public static int afLosange = 3; 
   final public static int afNorthTriangle = 4; 
   final public static int afSouthTriangle = 5; 
   final public static int afEastTriangle = 6; 
   final public static int afWestTriangle = 7; 
   final public static int afHexagon = 8; 
   final public static int afRectEdgeBump = 9; 
   final public static int afRectEdgeEtched = 10; 
   final public static int afRectEdgeRaised = 11; 
   final public static int afRectEdgeSunken = 12; 
   final public static int afTriangleRectangle = 13; 
   final public static int afPentagon = 14; 
   final public static int afOctogon = 15; 
   final public static int afProcess = 50; 
   final public static int afAlternateProcess = 51; 
   final public static int afDecision = 52; 
   final public static int afData = 53; 
   final public static int afPredefinedProcess = 54; 
   final public static int afInternalStorage = 55; 
   final public static int afDocument = 56; 
   final public static int afMultiDocument = 57; 
   final public static int afTermination = 58; 
   final public static int afPreparation = 59; 
   final public static int afManualInput = 60; 
   final public static int afManualOperation = 61; 
   final public static int afConnector = 62; 
   final public static int afOffPageConnection = 63; 
   final public static int afCard = 64; 
   final public static int afPunchedTape = 65; 
   final public static int afSummingJunction = 66; 
   final public static int afOr = 67; 
   final public static int afCollate = 68; 
   final public static int afSort = 69; 
   final public static int afExtract = 70; 
   final public static int afMerge = 71; 
   final public static int afStoredData = 72; 
   final public static int afDelay = 73; 
   final public static int afSequentialAccessStorage = 74; 
   final public static int afMagneticDisk = 75; 
   final public static int afDirectAccessStorage = 76; 
   final public static int afDisplay = 77; 
   final public static int afTransport = 78; 
   final public static int afProcessIso9000 = 79;
	public void addFlowListener(JxFlowListener listener);
	public void flowSave(String p_filename);
	public void flowLoad(String p_filename);
	public int nodeGetShape(String p_nodekey);
	public void nodeSetShape(String p_nodekey, int p_shape);
	public String nodeGetFillColor(String p_nodekey);
	public void nodeSetFillColor(String p_nodekey, int p_r, int p_g, int p_b);
	public String nodeGetText(String p_nodekey);
	public void nodeSetText(String p_nodekey, String p_text);
	public String linkGetText(String p_nodekey, String p_linkkey);
	public void linkSetText(String p_nodekey, String p_linkkey, String p_text);
	public void nodeCreate(String p_nodekey, double p_left, double p_top, double p_width, double p_height);
	public Vector getSelectedItems(); // vector of item key of type String 
	public int nodeDelete(String p_nodekey);
	public int linkDelete(String p_nodekey, String p_linkkey);
	public Vector flowTraverse(); // vector of node and item structure
	public void linkCreate(String p_orgNodeKey, String p_dstNodeKey, String p_linkKey);
}
