#define ini agent, if defined, obtain property from ini, otherwise obtain from property file

#iniAgent=afshk
#iniAgent=afsdev
#iniAgent=afsdev194
#iniAgent=afscn
#iniAgent=afstbdev
#iniAgent=afsdtmac
#iniAgent=afslive
#iniAgent=afsproxylive
#iniAgent=artwaydev
#iniAgent=artwaywglive
#iniAgent=artwayproxy
#iniAgent=clinicdev
#iniAgent=clinicerp
#iniAgent=clclaim
#iniAgent=clclaim2
#iniAgent=easyquo
#iniAgent=erpv4
#iniAgent=gbp
#iniAgent=gbpwip
#iniAgent=glhlv
#iniAgent=hapyikdev-162
#iniAgent=hapyik194
#iniAgent=hapyikeclipse
#iniAgent=hapyiktbeclipse
#iniAgent=hongwdev
#iniAgent=hongwproxylive
#iniAgent=kanghongdev
#iniAgent=kanghongdemo
#iniAgent=pmsdemo
#iniAgent=takfung
#iniAgent=wineac
#iniAgent=wineacdev
#iniAgent=wineaclivedev
#iniAgent=winecavedev
#iniAgent=winecaveeclipse
#iniAgent=wipdemo
#iniAgent=zkbi-admin-wp
#iniAgent=clerpctr
#iniAgent=clerpmk
#iniAgent=clerptst
#iniAgent=clerp2live
#iniAgent=clerptb
#iniAgent=clerpmulti
#iniAgent=clerpmultidev
#iniAgent=clerpmultilive
#iniAgent=clerpmultilivetb
#iniAgent=testonidev
#iniAgent=smartac
#iniAgent=smartacdev
#iniAgent=smartaceclipse
#iniAgent=smartacdev193
#iniAgent=jewelhk
#iniAgent=erpv4gbp
#iniAgent=edu
#iniAgent=axa
#iniAgent=axa2
#iniAgent=axaproxy
#iniAgent=chungkee
#iniAgent=mysqlerpv4
#iniAgent=aawdev
#iniAgent=scp0328
#iniAgent=integratec
#iniAgent=erpv4inv
#iniAgent=erpv4std
#iniAgent=erpv4afscn
#iniAgent=erpv4afscndev
#iniAgent=erpv4afscnlive
#iniAgent=erpv4ext
#iniAgent=vincero
#iniAgent=vincerobk
#iniAgent=vincerodev
#iniAgent=vincero-170
#iniAgent=vincero-72
#iniAgent=propertymgmt-170
#iniAgent=propertymgmt-demo
#iniAgent=propertymgmttb
#iniAgent=propertymgmtproxy
#iniAgent=hrdemo
#iniAgent=digiprt
#iniAgent=artwayerp
#iniAgent=artwayscp
#iniAgent=erpv4artway
#iniAgent=erpv4artwaylive
#iniAgent=winecaveerp
#iniAgent=bicore-mysql
#iniAgent=winecavescp
#iniAgent=winecaveerpnew
#iniAgent=bicore-mysql

iniAgent=saleorsync
#iniAgent=erpv4winecavenew



##allow update iniAgent by url parameter, should disable in production environment
iniAgentAllowUpdate=N

#allow agent has it own ini file (experimental feature) e.g. erpsetup.ini(master, erpsetup.ini.child1(agent)
iniAgentAllowChildIni=N

#if file exist, it will override webapps erpsetp.ini file
iniFile=/yic/v/unidev/wxcache/bischema/erpsetup.ini

#global flag for all agent
logButtonFlag=Y
