#***Testing***
#allowPayIPs=203.105.61.183-203.105.61.218

#allowPayIPs=18.140.106.57,18.142.92.184
#payUrl=https://test.paydollar.com/b2cDemo/eng/payment/payForm.jsp
#merchantId=88147448
#successUrl=http://dtqemu2.uniconn.com/winecave/orderpayok.html?type=paydollar
#failUrl=http://dtqemu2.uniconn.com/winecave/orderpayfail.html?type=paydollar
#cancelUrl=http://dtqemu2.uniconn.com/winecave/orderpaycancel.html?type=paydollar
#successChiUrl=http://dtqemu2.uniconn.com/winecave/chi/orderpayok.html?type=paydollar
#failChiUrl=http://dtqemu2.uniconn.com/winecave/chi/orderpayfail.html?type=paydollar
#cancelChiUrl=http://dtqemu2.uniconn.com/winecave/chi/orderpaycancel.html?type=paydollar
#*************

#***Production***
#allowPayIPs=103.149.149.1-103.149.149.62
allowPayIPs=18.140.106.57,18.142.92.184
payUrl=https://www.paydollar.com/b2c2/eng/payment/payForm.jsp
merchantId=88621887
#successUrl=https://hub.erpv4.com/winecave/orderpayok.html?type=paydollar
successUrl=https://winecavehk.com/hk/en/thank-you?type=paydollar
failUrl=https://winecavehk.com/hk/en/payment-failed?type=paydollar&status=Failed
cancelUrl=https://winecavehk.com/hk/en/payment-failed?type=paydollar&status=Cancelled
successChiUrl=https://winecavehk.com/zh-Hant/en/thank-you?type=paydollar
failChiUrl=https://winecavehk.com/hk/zh-Hant/payment-failed?type=paydollar&status=Failed
cancelChiUrl=https://winecavehk.com/hk/zh-Hant/payment-failed?type=paydollar&status=Cancelled
#****************

currCode=344
mpsMode=NIL
payType=N
payMethod=ALL
dataFeedLogFilePrefix=/yic/tmp/paydollar-datafeed-
orderRefPrefix=WCPD