rpcServerHost=192.168.19.206
#rpcServerHost=192.168.46.164
rpcServerPort=6002
databaseString=jdbc:scorpion:perfrpc:192.168.19.206:6002:gl:dbpath:/yic/v/erp_v3/data_wc:chaindir:-p /yic/v/erp_v3/src//invchn -p /yic/v/acc/src/chn -p /yic/v/acc/src/glchn
#databaseString=jdbc:scorpion:perfrpc:192.168.46.164:6002:gl:dbpath:/yic/v/erp_v3/data_wc:chaindir:-p /yic/v/erp_v3/src//invchn -p /yic/v/acc/src/chn -p /yic/v/acc/src/glchn
wineListTemplate=c:/tmp/winelist_template.xls
wineListFolder=c:/tmp
winecaveRSBaseUrl=http://localhost:8080/pmsdemo
winecaveRSBaseRemoteUrl=http://localhost:8080/pmsdemo
uniforceDatabaseName=newdemo_erp_v3
stockImagePath=/yic/v/erp_v3/message/STOCK_IMAGE
wineCaveContactEmail=general@winecavehk.com
ccy=HKD
quickSearchPriceMin=0
quickSearchPriceMax=5000
quickSearchPriceDefaultMin=0
quickSearchPriceDefaultMax=5000
allowOnlinePayment=Y
cashPaymentDiscount=0.03
#cashPaymentDiscount=0.00
allowChangePaymentMethod=N
regionLayoutVersion=2
sendSleep=800
sendBufLen=2048
cssVersion=191209a
databaseDriver=com.uniinformation.scorpion.driver.ScpDriver
databaseConnectionCount=3
maxDatabaseConnectionCount=6
winecaveRSExtraPhotosPath=rest/wcp/stocks
allowCaptcha=Y
captchaLength=5
excludeBins=('000001')