/* The following code was generated by JFlex 1.3.5 on 2/10/25 12:40 PM */

package com.kyoko.parser.graphql;
import java.io.*;
import com.kyoko.common.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 2/10/25 12:40 PM from the specification file
 * <tt>file:/yic/v/unidev/src/com/kyoko/parser/graphql/GraphQL.flex</tt>
 */
class Yylex {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int STRINGLITERAL = 1;
  final public static int STRINGLITERAL2 = 2;
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\10\0\1\41\1\40\1\1\2\0\1\2\22\0\1\40\1\36\1\42"+
    "\1\0\1\36\3\0\1\36\1\36\2\0\1\37\1\0\1\25\1\0"+
    "\12\24\1\36\2\0\1\36\2\0\1\36\1\23\1\34\1\23\1\35"+
    "\1\23\1\31\2\23\1\30\11\23\1\32\7\23\1\36\1\43\1\36"+
    "\1\0\1\23\1\0\1\12\1\17\1\20\1\23\1\5\1\26\1\33"+
    "\1\22\1\13\2\23\1\27\1\10\1\15\1\14\1\21\1\3\1\6"+
    "\1\16\1\11\1\4\3\23\1\7\1\23\1\36\1\0\1\36\uff82\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    36,    72,   108,   144,   180,   216,   252,   288,   324, 
      360,   396,   432,   468,   504,   540,   576,   612,   108,   648, 
      108,   684,   720,   108,   756,   792,   828,   864,   900,   936, 
      972,  1008,  1044,   432,  1080,  1116,   216,  1152,  1188,  1224, 
     1260,   108,   108,  1296,  1332,  1368,  1404,  1440,  1476,  1512, 
     1548,  1584,  1620,  1656,  1692,   108,   108,  1728,  1764,   216, 
      216,  1800,  1836,  1872,  1908,  1944,  1980,   216,  2016,   216, 
     2052,  2088,   216,  2124,  2160,  2196,  2232,   216,  2268,  2304, 
     2340,   216,  2376,  2412,  2448,  2484,   216
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\0\1\4\1\5\1\6\4\7\1\10\1\11\1\7"+
    "\1\12\2\7\1\13\5\7\1\14\1\15\1\16\1\7"+
    "\1\17\1\20\1\21\1\7\1\22\1\7\1\23\1\4"+
    "\1\24\1\25\1\26\1\0\42\27\1\30\1\31\42\27"+
    "\1\32\1\31\45\0\1\4\45\0\1\7\1\33\20\7"+
    "\1\0\10\7\11\0\22\7\1\0\10\7\11\0\1\7"+
    "\1\34\20\7\1\0\10\7\11\0\3\7\1\35\1\36"+
    "\15\7\1\0\10\7\11\0\12\7\1\37\7\7\1\0"+
    "\10\7\11\0\1\7\1\40\13\7\1\41\4\7\1\0"+
    "\10\7\32\0\1\14\1\42\42\0\1\42\22\0\7\7"+
    "\1\43\12\7\1\0\10\7\11\0\12\7\1\44\7\7"+
    "\1\0\7\7\1\45\11\0\22\7\1\0\1\7\1\46"+
    "\6\7\11\0\6\7\1\47\13\7\1\0\10\7\11\0"+
    "\11\7\1\50\10\7\1\0\10\7\46\0\1\24\45\0"+
    "\1\51\1\0\42\27\44\0\1\52\1\53\42\0\1\54"+
    "\4\0\2\7\1\55\17\7\1\0\10\7\11\0\6\7"+
    "\1\56\13\7\1\0\10\7\11\0\1\7\1\57\20\7"+
    "\1\0\10\7\11\0\16\7\1\60\3\7\1\0\10\7"+
    "\11\0\16\7\1\61\3\7\1\0\10\7\11\0\14\7"+
    "\1\62\5\7\1\0\10\7\11\0\17\7\1\63\2\7"+
    "\1\0\10\7\11\0\22\7\1\0\1\7\1\64\6\7"+
    "\11\0\6\7\1\45\13\7\1\0\10\7\11\0\11\7"+
    "\1\65\10\7\1\0\10\7\11\0\3\7\1\66\16\7"+
    "\1\0\10\7\11\0\11\7\1\67\10\7\1\0\10\7"+
    "\50\0\1\70\43\0\1\71\4\0\3\7\1\72\16\7"+
    "\1\0\10\7\11\0\7\7\1\73\12\7\1\0\10\7"+
    "\11\0\2\7\1\74\17\7\1\0\10\7\11\0\2\7"+
    "\1\75\17\7\1\0\10\7\11\0\1\7\1\76\20\7"+
    "\1\0\10\7\11\0\13\7\1\77\6\7\1\0\10\7"+
    "\11\0\2\7\1\100\17\7\1\0\10\7\11\0\13\7"+
    "\1\101\6\7\1\0\10\7\11\0\7\7\1\44\12\7"+
    "\1\0\10\7\11\0\10\7\1\102\11\7\1\0\10\7"+
    "\11\0\22\7\1\0\1\7\1\103\6\7\11\0\4\7"+
    "\1\104\15\7\1\0\10\7\11\0\6\7\1\105\13\7"+
    "\1\0\10\7\11\0\6\7\1\106\13\7\1\0\10\7"+
    "\11\0\15\7\1\107\4\7\1\0\10\7\11\0\5\7"+
    "\1\110\14\7\1\0\10\7\11\0\2\7\1\111\17\7"+
    "\1\0\10\7\11\0\12\7\1\112\7\7\1\0\10\7"+
    "\11\0\2\7\1\113\17\7\1\0\10\7\11\0\10\7"+
    "\1\114\11\7\1\0\10\7\11\0\3\7\1\115\16\7"+
    "\1\0\10\7\11\0\7\7\1\116\12\7\1\0\10\7"+
    "\11\0\22\7\1\0\5\7\1\45\2\7\11\0\7\7"+
    "\1\117\12\7\1\0\10\7\11\0\11\7\1\120\10\7"+
    "\1\0\10\7\11\0\10\7\1\121\11\7\1\0\10\7"+
    "\11\0\12\7\1\45\7\7\1\0\10\7\11\0\12\7"+
    "\1\122\7\7\1\0\10\7\11\0\16\7\1\123\3\7"+
    "\1\0\10\7\11\0\6\7\1\124\13\7\1\0\10\7"+
    "\11\0\10\7\1\125\11\7\1\0\10\7\11\0\11\7"+
    "\1\126\10\7\1\0\10\7\11\0\12\7\1\127\7\7"+
    "\1\0\10\7\6\0";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  0,  0,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  9,  1,  9,  1,  1,  9,  0,  0,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  0,  9,  9,  0,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  9,  9,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
  StringBuffer sb = new StringBuffer();
  private Parser yyparser;

  public Yylex(java.io.Reader r, Parser yyparser) {
    this(r);
    this.yyparser = yyparser;
  }
	public int getCurrentPos() {
  		return(yy_currentPos);
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Yylex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[2520];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 140) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 22: 
          {  sb.append(yytext()); CoreLog.log("xxx");  }
        case 88: break;
        case 81: 
          {  return Parser.MUTATION;  }
        case 89: break;
        case 21: 
          {  sb.setLength(0); yybegin(STRINGLITERAL);  }
        case 90: break;
        case 11: 
          {  
				yyparser.yylval = new ParserVal(Integer.parseInt(yytext()));
         	return Parser.INT; 
			 }
        case 91: break;
        case 55: 
          {  sb.setLength(0); yybegin(STRINGLITERAL2);  }
        case 92: break;
        case 5: 
        case 6: 
        case 7: 
        case 8: 
        case 9: 
        case 10: 
        case 13: 
        case 14: 
        case 15: 
        case 16: 
        case 17: 
        case 26: 
        case 27: 
        case 28: 
        case 29: 
        case 30: 
        case 31: 
        case 32: 
        case 34: 
        case 35: 
        case 37: 
        case 38: 
        case 39: 
        case 44: 
        case 45: 
        case 46: 
        case 47: 
        case 48: 
        case 49: 
        case 50: 
        case 51: 
        case 52: 
        case 53: 
        case 54: 
        case 57: 
        case 58: 
        case 61: 
        case 62: 
        case 63: 
        case 64: 
        case 65: 
        case 66: 
        case 68: 
        case 70: 
        case 71: 
        case 73: 
        case 74: 
        case 75: 
        case 76: 
        case 78: 
        case 79: 
        case 80: 
        case 82: 
        case 83: 
        case 84: 
        case 85: 
          {  
         	yyparser.yylval = new ParserVal(new LexIdent(yytext()));
         	return Parser.IDENT; 
			 }
        case 93: break;
        case 36: 
          {  
         	yyparser.yylval = new ParserVal(new LexIdent(yytext()));
         	return Parser.SCALER; 
			 }
        case 94: break;
        case 41: 
          {  sb.append("\"");  }
        case 95: break;
        case 42: 
          {  sb.append("\\");  }
        case 96: break;
        case 86: 
          {  return Parser.SUBSCRIPTION;  }
        case 97: break;
        case 56: 
          {  yybegin(YYINITIAL); 
          yyparser.yylval = new ParserVal(sb.toString());
	  CoreLog.log("return long texts");
          return Parser.STRING;
	      }
        case 98: break;
        case 20: 
          {  System.err.println("Sorry, backspace doesn't work");  }
        case 99: break;
        case 19: 
          {   }
        case 100: break;
        case 12: 
        case 18: 
          {  return (int) yycharat(0);  }
        case 101: break;
        case 3: 
        case 4: 
          {   }
        case 102: break;
        case 33: 
          {  
				yyparser.yylval = new ParserVal(Double.parseDouble(yytext()));
         	return Parser.FLOAT; 
			 }
        case 103: break;
        case 77: 
          {  return Parser.SCHEMA;  }
        case 104: break;
        case 72: 
          {  return Parser.FALSE;  }
        case 105: break;
        case 69: 
          {  return Parser.INPUT;  }
        case 106: break;
        case 67: 
          {  return Parser.QUERY;  }
        case 107: break;
        case 23: 
          {  yybegin(YYINITIAL); 
          yyparser.yylval = new ParserVal(sb.toString());
          return Parser.STRING;
	      }
        case 108: break;
        case 59: 
          {  return Parser.TRUE;  }
        case 109: break;
        case 60: 
          {  return Parser.TYPE;  }
        case 110: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              { return 0; }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
